### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by alfonsotech** [jayzamazing/Restaurant-POS#2]
Can you please put this branch in the gh-pages so we can test it? Tried to access this http://jayzamazing.github.io/meal-calculator .
This is related to PR #1.

**Comment by jayzamazing** [comment]
This is a node project. This is not a project that can be put up on gh-pages, needs to be put on a server and since gh-pages does not act as a server, this request cannot be fullfilled. This project is currently in development and will be put up on a server when closer to completion.
