### ISSUE TITLE
CORS is cool, but opens up some security vulnerabilities

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Restaurant-POS#44]
If anyone can post from anywhere, that's no good. When using CORS, you should have a whitelist of what hosts can touch the app 
yours: https://github.com/jayzamazing/Restaurant-POS/blob/master/src/app.js#L23
whitelist example: https://github.com/expressjs/cors#configuring-cors-w-dynamic-origin

**Comment by jayzamazing** [comment]
Removed cors in https://github.com/jayzamazing/Restaurant-POS/pull/62.
